version: 2
updates:
  # Enable version updates for base npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      base-npm-all:
        patterns:
          - "*"
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-all:
        patterns:
          - "*"
  # Enable version updates for automations uv
  - package-ecosystem: "uv"
    directory: "/automations/"
    schedule:
      interval: "weekly"
    groups:
      automations-uv-all:
        patterns:
          - "*"
  # Enable version updates for examples uv
  - package-ecosystem: "uv"
    directory: "/examples/developer-hub-python/"
    schedule:
      interval: "weekly"
    groups:
      examples-uv-all:
        patterns:
          - "*"
  # Enable version updates for examples js
  - package-ecosystem: "npm"
    directory: "/examples/developer-hub-javascript/"
    schedule:
      interval: "weekly"
    groups:
      examples-js-all:
        patterns:
          - "*"
  # Enable version updates for examples go
  - package-ecosystem: "gomod"
    directory: "/examples/developer-hub-go/"
    schedule:
      interval: "weekly"
    groups:
      examples-go-all:
        patterns:
          - "*"
  # Enable version updates for examples rust
  - package-ecosystem: "cargo"
    directory: "/examples/developer-hub-rust/"
    schedule:
      interval: "weekly"
    groups:
      examples-rust-all:
        patterns:
          - "*"
