base_url = "https://dev.flare.network/"
verbose = "info"
cache = true
accept = ["200", "429", "403"]
no_progress = true
exclude = [
    '^/',
    'https://dev\.flare\.network/',
    'https?://localhost(?::[0-9]+)?/',
    'https://fdc-verifiers-testnet\.flare\.network/',
    'https://github\.com/flare-foundation/flare-hardhat-starter/',
    'https://github\.com/flare-foundation/flare-foundry-starter/',
    'https://sepolia\.etherscan\.io/',
    'https://metamask\.io/',
    'https://openweathermap\.org/',
    'https://www\.gnu\.org/',
    'https://swapi\.dev/',
]
