name: Automatic Feed Request

on:
  schedule:
    # Once per day at 03:00 UTC
    - cron: "0 3 * * *"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  check_and_report:
    name: Run automatic feed request
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    defaults:
      run:
        working-directory: ./automations
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          enable-cache: true
      - name: Install dependencies
        run: uv sync
      - name: Check for new feeds
        run: uv run check_new_feed.py
        id: feed
      - name: Create issue
        uses: JasonEtco/create-an-issue@v2
        if: steps.feed.outcome == 'success' && steps.feed.conclusion != 'neutral'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: automations/issues.md
