name: Automatic Feed Request

on:
  push:
    branches:
      - main

permissions:
  contents: read
  issues: write

jobs:
  check_and_report:
    name: Run automatic feed request
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./automations
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          enable-cache: true
      - name: Install dependencies
        run: uv sync
      - name: Generate issues file
        run: uv run check_new_feed.py
      - name: Check if issues file is empty
        id: check_file
        run: |
          if [ -s "automations/issues.md" ]; then
            echo "file_is_empty=false" >> $GITHUB_OUTPUT
          else
            echo "file_is_empty=true" >> $GITHUB_OUTPUT
          fi
      - name: Create issue
        uses: JasonEtco/create-an-issue@v2
        if: steps.check_file.outputs.file_is_empty == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: automations/issues.md
